"use client";

import { AlertTriangle, CheckCircle2, Copy, ShieldCheck } from "lucide-react";
import { ArtifactToolbar } from "@/components/product/artifact-toolbar";
import { useFeedback } from "@/components/product/feedback";
import { useKit } from "@/components/product/kit-context";
import { Banner, Button, Card } from "@/components/ui/primitives";
import type { InterviewPrepArtifact, InterviewQuestion } from "@/lib/api-types";
import { copyText, safeFilename } from "@/lib/product";

export function InterviewWorkspace({ artifact, company, role }: { artifact: InterviewPrepArtifact; company: string; role: string }) {
  const { notify } = useFeedback();
  const { openEvidence } = useKit();
  const exportText = interviewText(artifact);
  const groups = groupQuestions(artifact.questions);

  async function copyAnswer(question: InterviewQuestion) {
    try { await copyText(question.answer_guide.suggested_answer); notify("Suggested answer copied."); } catch { notify("Copy failed. Your browser may have blocked clipboard access.", "error"); }
  }

  return <div>
    <ArtifactToolbar title="Interview preparation" validation={artifact.validation} claims={artifact.claims} text={exportText} filename={safeFilename(company, role, "interview-prep")} />
    <Banner tone="neutral" title="Strategy.">{artifact.strategy_summary || "No strategy summary was returned."}</Banner>
    {artifact.focus_areas.length > 0 && <section className="mt-5" aria-labelledby="focus-heading"><h2 id="focus-heading" className="mb-3 text-md font-semibold">Focus areas</h2><div className="grid gap-3 md:grid-cols-2">{artifact.focus_areas.map((area) => <Card key={`${area.requirement_id}-${area.topic}`} className="shadow-none"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{area.topic}</h3><span className="rounded-pill border border-neutral-border bg-neutral-bg px-2.5 py-1 text-xs font-semibold capitalize text-neutral">{area.priority}</span></div><p className="mt-2 text-sm text-ink-secondary">{area.guidance}</p><p className="mt-2 text-xs capitalize text-ink-muted">Classification: {area.classification.replaceAll("_", " ")}</p></Card>)}</div></section>}
    <section className="mt-6" aria-labelledby="questions-heading"><h2 id="questions-heading" className="mb-3 text-md font-semibold">Interview questions</h2>{artifact.questions.length ? <div className="space-y-4">{Array.from(groups.entries()).map(([category, questions]) => <div key={category}><h3 className="mb-2 text-xs font-semibold uppercase tracking-[0.06em] text-ink-muted">{category.replaceAll("_", " ")} · {questions.length}</h3><div className="space-y-2">{questions.map((question) => <details key={question.id} className="rounded-md border border-border bg-surface"><summary className="flex min-h-12 cursor-pointer items-center gap-3 px-4 py-3 font-medium"><span className="flex-1">{question.question}</span><span className="rounded-pill border border-neutral-border bg-neutral-bg px-2 py-0.5 text-xs capitalize text-neutral">{question.priority}</span></summary><div className="border-t border-border-subtle px-4 py-4"><p className="text-sm text-ink-secondary">{question.rationale}</p><GuideList title="Key points" values={question.answer_guide.key_points} /><GuideList title="Avoid" values={question.answer_guide.statements_to_avoid} warning />{question.answer_guide.honest_gap_language && <Banner tone="warning" className="mt-3" title="Honest gap language.">{question.answer_guide.honest_gap_language}</Banner>}<div className="mt-4 rounded-md border border-border-subtle bg-surface-subtle p-4"><p className="text-xs font-semibold uppercase tracking-[0.05em] text-ink-muted">Suggested answer</p><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed">{question.answer_guide.suggested_answer || "No suggested answer was returned."}</p></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => void copyAnswer(question)} disabled={!question.answer_guide.suggested_answer}><Copy aria-hidden="true" className="size-4" />Copy answer</Button>{(question.evidence.length > 0 || question.answer_guide.evidence.length > 0) && <Button size="sm" variant="ghost" onClick={() => openEvidence()}><ShieldCheck aria-hidden="true" className="size-4" />Evidence</Button>}</div></div></details>)}</div></div>)}</div> : <Card><p className="text-sm text-ink-muted">No interview questions were returned.</p></Card>}</section>
    <section className="mt-6" aria-labelledby="star-heading"><h2 id="star-heading" className="mb-3 text-md font-semibold">STAR candidates</h2><div className="space-y-3">{artifact.star_stories.length ? artifact.star_stories.map((story) => <Card key={story.id} className="shadow-none"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{story.title_or_degree || story.employer_or_institution || "Supported STAR candidate"}</h3><p className="text-xs capitalize text-ink-muted">{story.source_type.replaceAll("_", " ")}</p></div>{story.completeness === "complete" ? <span className="inline-flex items-center gap-1.5 rounded-pill border border-positive-border bg-positive-bg px-2.5 py-1 text-xs font-semibold text-positive"><CheckCircle2 aria-hidden="true" className="size-3.5" />Complete supported story</span> : <span className="inline-flex items-center gap-1.5 rounded-pill border border-warning-border bg-warning-bg px-2.5 py-1 text-xs font-semibold text-warning"><AlertTriangle aria-hidden="true" className="size-3.5" />Incomplete · {story.missing_components.join(", ")}</span>}</div><dl className="mt-4 grid grid-cols-[32px_1fr] gap-x-3 gap-y-2 text-sm"><StarRow label="S" value={story.situation} /><StarRow label="T" value={story.task} /><StarRow label="A" value={story.action} /><StarRow label="R" value={story.result} /></dl>{story.safe_usage_guidance && <p className="mt-3 text-xs text-ink-muted">{story.safe_usage_guidance}</p>}</Card>) : <Card><p className="text-sm text-ink-muted">No supported STAR candidates were returned.</p></Card>}</div></section>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><Card className="shadow-none"><h2 className="text-md font-semibold">Technical study topics</h2><p className="mt-1 text-xs text-ink-muted">Preparation topics are not candidate experience.</p>{artifact.technical_study_topics.length ? <ul className="mt-3 space-y-3">{artifact.technical_study_topics.map((topic) => <li key={`${topic.requirement_id}-${topic.topic}`}><p className="font-medium">{topic.topic}</p><p className="text-sm text-ink-secondary">{topic.reason}</p><p className="mt-1 text-xs text-warning">Boundary: {topic.boundary}</p></li>)}</ul> : <p className="mt-3 text-sm text-ink-muted">None returned.</p>}</Card><Card className="shadow-none"><h2 className="text-md font-semibold">Honest gap guidance</h2>{artifact.gap_handling.length ? <ul className="mt-3 space-y-3">{artifact.gap_handling.map((gap) => <li key={gap.requirement_id}><p className="font-medium">{gap.requirement}{gap.must_have ? " · must-have" : ""}</p><p className="text-sm text-ink-secondary">{gap.guidance}</p>{gap.what_to_avoid.length > 0 && <p className="mt-1 text-xs text-danger">Avoid: {gap.what_to_avoid.join(" · ")}</p>}</li>)}</ul> : <p className="mt-3 text-sm text-ink-muted">None returned.</p>}</Card></div>
    <section className="mt-6" aria-labelledby="ask-heading"><h2 id="ask-heading" className="mb-3 text-md font-semibold">Questions for the interviewer</h2><div className="grid gap-3 md:grid-cols-2">{artifact.interviewer_questions.map((question) => <Card key={question.id} className="shadow-none"><p className="font-medium">{question.question}</p><p className="mt-2 text-sm text-ink-secondary">{question.rationale}</p><p className="mt-2 text-xs text-ink-muted">Source: {question.source}</p></Card>)}</div></section>
  </div>;
}

function GuideList({ title, values, warning = false }: { title: string; values: string[]; warning?: boolean }) { if (!values.length) return null; return <div className="mt-3"><p className={`text-xs font-semibold uppercase tracking-[0.05em] ${warning ? "text-warning" : "text-ink-muted"}`}>{title}</p><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{values.map((value) => <li key={value}>{value}</li>)}</ul></div>; }
function StarRow({ label, value }: { label: string; value: string }) { return <><dt className="font-mono font-semibold text-accent">{label}</dt><dd>{value || <span className="text-ink-muted">Not evidenced—left blank rather than invented.</span>}</dd></>; }
function groupQuestions(questions: InterviewQuestion[]): Map<string, InterviewQuestion[]> { const groups = new Map<string, InterviewQuestion[]>(); for (const question of questions) { const group = groups.get(question.category); if (group) group.push(question); else groups.set(question.category, [question]); } return groups; }
function interviewText(artifact: InterviewPrepArtifact): string { const lines = ["INTERVIEW PREPARATION", "", `Strategy: ${artifact.strategy_summary}`, "", "QUESTIONS"]; for (const question of artifact.questions) lines.push("", `[${question.category}] ${question.question}`, `Suggested answer: ${question.answer_guide.suggested_answer}`, question.answer_guide.honest_gap_language ? `Honest gap language: ${question.answer_guide.honest_gap_language}` : ""); lines.push("", "STAR CANDIDATES"); for (const story of artifact.star_stories) lines.push("", `${story.title_or_degree || story.employer_or_institution} — ${story.completeness}`, `S: ${story.situation}`, `T: ${story.task}`, `A: ${story.action}`, `R: ${story.result || "Not evidenced"}`); lines.push("", "QUESTIONS FOR THE INTERVIEWER", ...artifact.interviewer_questions.map((question) => `- ${question.question} — ${question.rationale}`)); return lines.filter((line, index) => line !== "" || lines[index - 1] !== "").join("\n"); }
