"use client";

import { AlertTriangle, CheckCircle2, Info, ShieldCheck } from "lucide-react";
import { ArtifactToolbar } from "@/components/product/artifact-toolbar";
import { useKit } from "@/components/product/kit-context";
import { TrustSummary } from "@/components/product/trust-summary";
import { useArtifactView } from "@/components/product/use-artifact-view";
import { Banner, Card } from "@/components/ui/primitives";
import type { JobFitArtifact } from "@/lib/api-types";
import { safeFilename } from "@/lib/product";

export function JobFitWorkspace({ artifact, company, role }: { artifact: JobFitArtifact; company: string; role: string }) {
  const { openEvidence } = useKit();
  const [view, setView] = useArtifactView();
  const exportText = jobFitText(artifact);
  const score = Math.max(0, Math.min(100, artifact.requirement_coverage_score));
  return <div>
    <ArtifactToolbar title="Job fit" validation={artifact.validation} claims={artifact.claims} text={exportText} filename={safeFilename(company, role, "job-fit")} view={view} onViewChange={setView} />
    {view === "trust" ? <TrustSummary title="Job fit" claims={artifact.claims} validation={artifact.validation} text={exportText} readinessLabel={`Fit band: ${artifact.fit_band}`} explanation="Fit band, coverage, and ATS keyword values are deterministic engine outputs. The trace and validation counts below are presentation aggregates, not an AI-confidence score." onOpenContent={() => setView("content")} /> : <>
    {artifact.must_have_gaps.length > 0 && <Banner tone="warning" title="Must-have gap.">{artifact.must_have_gaps.join(" · ")} — the backend classified this as unsupported, so it must be addressed honestly.</Banner>}
    <Card className="mt-5"><div className="grid items-center gap-6 md:grid-cols-[144px_1fr]"><div className="grid size-32 place-items-center rounded-pill" style={{ background: `conic-gradient(var(--accent) ${score}%, var(--surface-raised) 0)` }} aria-label={`Requirement coverage ${artifact.requirement_coverage_score}`}><div className="grid size-24 place-items-center rounded-pill bg-surface text-center"><div><p className="font-mono text-2xl font-semibold leading-none">{artifact.requirement_coverage_score}</p><p className="mt-1 text-[10px] uppercase tracking-[0.06em] text-ink-muted">coverage</p></div></div></div><div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-pill border border-positive-border bg-positive-bg px-2.5 py-1 text-xs font-semibold capitalize text-positive"><CheckCircle2 aria-hidden="true" className="size-3.5" />{artifact.fit_band}</span><span className="font-mono text-xs text-ink-muted">Original-resume keyword score {artifact.ats_keyword_score}</span></div><p className="mt-3 text-pretty text-base text-ink-secondary">{artifact.summary}</p><p className="mt-3 text-xs text-ink-muted">Requirement coverage is a reproducible policy index—not AI confidence, a probability, or a guarantee.</p></div></div></Card>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><TagCard title="Strongest matches" values={artifact.strongest_matches} tone="positive" /><TagCard title="Adjacent capabilities" values={artifact.adjacent_capabilities} tone="warning" /><TagCard title="Working knowledge" values={artifact.working_knowledge} tone="warning" /><TagCard title="Genuine gaps" values={artifact.genuine_gaps} tone="danger" /></div>
    <Card className="mt-5 shadow-none"><h2 className="text-md font-semibold">Positioning recommendations</h2>{artifact.positioning_recommendations.length ? <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{artifact.positioning_recommendations.map((recommendation) => <li key={`${recommendation.requirement_id}-${recommendation.text}`}>{recommendation.text}</li>)}</ol> : <p className="mt-2 text-sm text-ink-muted">No recommendations were returned.</p>}</Card>
    <section className="mt-6" aria-labelledby="requirements-heading"><h2 id="requirements-heading" className="mb-3 text-md font-semibold">Requirement assessments</h2><div className="overflow-x-auto rounded-lg border border-border bg-surface"><table className="min-w-[760px] w-full border-collapse text-sm"><thead><tr className="border-b border-border bg-surface-subtle text-left text-xs uppercase tracking-[0.05em] text-ink-muted"><th className="px-4 py-3">Requirement</th><th className="px-4 py-3">Importance</th><th className="px-4 py-3">Classification</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Evidence</th></tr></thead><tbody>{artifact.requirements.map((requirement) => <tr key={requirement.id} className="border-b border-border-subtle last:border-0"><td className="px-4 py-3"><p className="font-medium">{requirement.requirement}</p>{requirement.must_have && <p className="mt-1 font-mono text-[10px] font-semibold text-danger">MUST-HAVE</p>}<p className="mt-1 text-xs text-ink-muted">{requirement.explanation}</p></td><td className="px-4 py-3 capitalize">{requirement.importance}</td><td className="px-4 py-3"><Classification value={requirement.classification} /></td><td className="px-4 py-3 capitalize">{requirement.risk.replaceAll("_", " ")}</td><td className="px-4 py-3">{requirement.evidence.length ? <button type="button" onClick={() => openEvidence()} className="inline-flex min-h-11 items-center gap-2 rounded-control px-2 font-semibold text-accent hover:bg-accent-subtle"><ShieldCheck aria-hidden="true" className="size-4" />Evidence</button> : <span className="text-ink-muted">None</span>}</td></tr>)}</tbody></table></div></section>
    {!artifact.consistency.passed && <Banner tone="danger" className="mt-5" title="Consistency validation failed.">This artifact should not be treated as deliverable.</Banner>}
    </>}
  </div>;
}

function TagCard({ title, values, tone }: { title: string; values: string[]; tone: "positive" | "warning" | "danger" }) { const classes = tone === "positive" ? "border-positive-border bg-positive-bg text-positive" : tone === "warning" ? "border-warning-border bg-warning-bg text-warning" : "border-danger-border bg-danger-bg text-danger"; return <Card className="shadow-none"><h3 className="font-semibold">{title}</h3><div className="mt-3 flex flex-wrap gap-2">{values.length ? values.map((value) => <span key={value} className={`rounded-pill border px-2.5 py-1 text-sm ${classes}`}>{value}</span>) : <span className="text-sm text-ink-muted">None returned</span>}</div></Card>; }
function Classification({ value }: { value: string }) { const danger = value.includes("gap"); const adjacent = value.includes("adjacent") || value.includes("working"); const Icon = danger ? AlertTriangle : adjacent ? Info : CheckCircle2; return <span className={`inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-1 text-xs font-semibold capitalize ${danger ? "border-danger-border bg-danger-bg text-danger" : adjacent ? "border-warning-border bg-warning-bg text-warning" : "border-positive-border bg-positive-bg text-positive"}`}><Icon aria-hidden="true" className="size-3.5" />{value.replaceAll("_", " ")}</span>; }
function jobFitText(artifact: JobFitArtifact): string { return [`JOB FIT — ${artifact.fit_band}`, `Requirement coverage: ${artifact.requirement_coverage_score}`, `Original-resume keyword score: ${artifact.ats_keyword_score}`, "", artifact.summary, "", "Strongest matches:", ...artifact.strongest_matches.map((item) => `- ${item}`), "", "Adjacent capabilities:", ...artifact.adjacent_capabilities.map((item) => `- ${item}`), "", "Working knowledge:", ...artifact.working_knowledge.map((item) => `- ${item}`), "", "Genuine gaps:", ...artifact.genuine_gaps.map((item) => `- ${item}`), "", "Must-have gaps:", ...artifact.must_have_gaps.map((item) => `- ${item}`), "", "Recommendations:", ...artifact.positioning_recommendations.map((item) => `- ${item.text}`)].filter((line, index, lines) => line !== "" || lines[index - 1] !== "").join("\n"); }
