"""The versioned ApplicationKit contract and grounded generation orchestration.

Public surface through Phase 2B2. Callers (the API service, the worker, tests) should
import from here rather than from private submodules.

- :func:`generate_application_kit` — the single orchestration entry point.
- :class:`ApplicationKit` and its artifact/claim/validation models — the typed,
  versioned, JSON-serializable contract.
- :func:`application_kit_to_dict` / :func:`normalize_persisted_result` — the
  serialization boundary (including Phase 1 legacy compatibility).
"""

from __future__ import annotations

from ats_engine.kit.contract import (
    APPLICATION_KIT_V1,
    APPLICATION_KIT_V2,
    ORCHESTRATION_VERSION,
    SCHEMA_VERSION,
    AnswerArtifact,
    AnswerItem,
    ApplicationKit,
    ArtifactKind,
    ArtifactStatus,
    ArtifactValidation,
    ClaimRecord,
    ClaimStatus,
    ClaimType,
    ConsistencyValidation,
    CoverLetterArtifact,
    EvidenceRef,
    FitBand,
    GapHandlingGuide,
    GenerationMetadata,
    InterviewAnswerGuide,
    InterviewerQuestion,
    InterviewFocusArea,
    InterviewPrepArtifact,
    InterviewPriority,
    InterviewQuestion,
    InterviewQuestionCategory,
    JobFitArtifact,
    PositioningRecommendation,
    RequirementAssessment,
    RequirementClassification,
    RequirementRisk,
    ResumeArtifact,
    StarCompleteness,
    StarSourceType,
    StarStoryCandidate,
    TechnicalStudyTopic,
    ValidationSummary,
)
from ats_engine.kit.orchestrator import generate_application_kit
from ats_engine.kit.serialization import (
    LEGACY_SCHEMA_VERSION,
    application_kit_from_dict,
    application_kit_to_dict,
    is_application_kit_v1,
    is_application_kit_v2,
    is_application_kit_v3,
    normalize_persisted_result,
)

__all__ = [
    "ORCHESTRATION_VERSION",
    "APPLICATION_KIT_V1",
    "APPLICATION_KIT_V2",
    "SCHEMA_VERSION",
    "LEGACY_SCHEMA_VERSION",
    "AnswerArtifact",
    "AnswerItem",
    "ApplicationKit",
    "ArtifactKind",
    "ArtifactStatus",
    "ArtifactValidation",
    "ClaimRecord",
    "ClaimStatus",
    "ClaimType",
    "CoverLetterArtifact",
    "EvidenceRef",
    "GenerationMetadata",
    "GapHandlingGuide",
    "InterviewAnswerGuide",
    "InterviewFocusArea",
    "InterviewPrepArtifact",
    "InterviewPriority",
    "InterviewQuestion",
    "InterviewQuestionCategory",
    "InterviewerQuestion",
    "ConsistencyValidation",
    "FitBand",
    "JobFitArtifact",
    "PositioningRecommendation",
    "RequirementAssessment",
    "RequirementClassification",
    "RequirementRisk",
    "ResumeArtifact",
    "StarCompleteness",
    "StarSourceType",
    "StarStoryCandidate",
    "TechnicalStudyTopic",
    "ValidationSummary",
    "generate_application_kit",
    "application_kit_from_dict",
    "application_kit_to_dict",
    "is_application_kit_v1",
    "is_application_kit_v2",
    "is_application_kit_v3",
    "normalize_persisted_result",
]
