"""The versioned ApplicationKit contract and grounded generation orchestration.

Public surface through Phase 2B3. Callers (the API service, the worker, tests) should
import from here rather than from private submodules.

- :func:`generate_application_kit` — the single orchestration entry point.
- :class:`ApplicationKit` and its artifact/claim/validation models — the typed,
  versioned, JSON-serializable contract.
- :func:`application_kit_to_dict` / :func:`normalize_persisted_result` — the
  serialization boundary (including Phase 1 legacy compatibility).
"""

from __future__ import annotations

from ats_engine.kit.change_actions import (
    ChangeAction,
    ChangeActionResult,
    apply_change_actions,
)
from ats_engine.kit.contract import (
    APPLICATION_KIT_V1,
    APPLICATION_KIT_V2,
    APPLICATION_KIT_V3,
    APPLICATION_KIT_V4,
    ORCHESTRATION_VERSION,
    SCHEMA_VERSION,
    AnswerArtifact,
    AnswerItem,
    ApplicationKit,
    ArtifactKind,
    ArtifactStatus,
    ArtifactValidation,
    AtsMatchScore,
    AtsQualityReportPayload,
    ChangeOperation,
    ChangeRecord,
    ChangeStatus,
    ChangeType,
    ClaimRecord,
    ClaimStatus,
    ClaimType,
    ConsistencyValidation,
    CoverLetterArtifact,
    CoverLetterDocument,
    EvidenceRef,
    FitBand,
    FitCategory,
    GapHandlingGuide,
    GenerationMetadata,
    InterviewAnswerGuide,
    InterviewerQuestion,
    InterviewFocusArea,
    InterviewPrepArtifact,
    InterviewPriority,
    InterviewQuestion,
    InterviewQuestionCategory,
    JobFitArtifact,
    LinkedInOutreachArtifact,
    MatchReport,
    OutreachAudience,
    OutreachContext,
    OutreachContextKind,
    OutreachContextRef,
    OutreachDraft,
    OutreachFormat,
    OutreachIntent,
    PositioningRecommendation,
    RelationshipValidation,
    RequirementAssessment,
    RequirementClassification,
    RequirementRisk,
    ResumeArtifact,
    ResumeCertificationEntry,
    ResumeDocument,
    ResumeEducationEntry,
    ResumeExperienceEntry,
    ResumeSkillGroup,
    ScoreConfidence,
    StageTimings,
    StarCompleteness,
    StarSourceType,
    StarStoryCandidate,
    TechnicalStudyTopic,
    ValidationSummary,
    WeightedKeyword,
)
from ats_engine.kit.orchestrator import generate_application_kit
from ats_engine.kit.serialization import (
    LEGACY_SCHEMA_VERSION,
    application_kit_from_dict,
    application_kit_to_dict,
    is_application_kit_v1,
    is_application_kit_v2,
    is_application_kit_v3,
    is_application_kit_v4,
    is_application_kit_v5,
    normalize_persisted_result,
)

__all__ = [
    "ORCHESTRATION_VERSION",
    "APPLICATION_KIT_V1",
    "APPLICATION_KIT_V2",
    "APPLICATION_KIT_V3",
    "APPLICATION_KIT_V4",
    "SCHEMA_VERSION",
    "LEGACY_SCHEMA_VERSION",
    "AnswerArtifact",
    "AnswerItem",
    "ApplicationKit",
    "ArtifactKind",
    "ArtifactStatus",
    "ArtifactValidation",
    "AtsMatchScore",
    "AtsQualityReportPayload",
    "ChangeAction",
    "ChangeActionResult",
    "ChangeOperation",
    "ChangeRecord",
    "ChangeStatus",
    "ChangeType",
    "ClaimRecord",
    "ClaimStatus",
    "ClaimType",
    "CoverLetterArtifact",
    "CoverLetterDocument",
    "EvidenceRef",
    "FitCategory",
    "MatchReport",
    "ScoreConfidence",
    "StageTimings",
    "WeightedKeyword",
    "GenerationMetadata",
    "GapHandlingGuide",
    "apply_change_actions",
    "is_application_kit_v5",
    "InterviewAnswerGuide",
    "InterviewFocusArea",
    "InterviewPrepArtifact",
    "InterviewPriority",
    "InterviewQuestion",
    "InterviewQuestionCategory",
    "InterviewerQuestion",
    "ConsistencyValidation",
    "FitBand",
    "JobFitArtifact",
    "LinkedInOutreachArtifact",
    "OutreachAudience",
    "OutreachContext",
    "OutreachContextKind",
    "OutreachContextRef",
    "OutreachDraft",
    "OutreachFormat",
    "OutreachIntent",
    "PositioningRecommendation",
    "RequirementAssessment",
    "RequirementClassification",
    "RequirementRisk",
    "RelationshipValidation",
    "ResumeArtifact",
    "ResumeCertificationEntry",
    "ResumeDocument",
    "ResumeEducationEntry",
    "ResumeExperienceEntry",
    "ResumeSkillGroup",
    "StarCompleteness",
    "StarSourceType",
    "StarStoryCandidate",
    "TechnicalStudyTopic",
    "ValidationSummary",
    "generate_application_kit",
    "application_kit_from_dict",
    "application_kit_to_dict",
    "is_application_kit_v1",
    "is_application_kit_v2",
    "is_application_kit_v3",
    "is_application_kit_v4",
    "normalize_persisted_result",
]
